"""Initial database schema

Revision ID: 39d07401d54b
Revises:
Create Date: 2026-02-27 21:54:05.106389

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "39d07401d54b"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("category_id", sa.UUID(), nullable=False),
        sa.Column("category_name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("category_id"),
        sa.UniqueConstraint("category_name"),
    )
    op.create_table(
        "kiosks",
        sa.Column("kiosk_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("location_description", sa.String(length=255), nullable=False),
        sa.Column(
            "kiosk_status",
            sa.Enum("ONLINE", "OFFLINE", "MAINTENANCE", name="kioskstatus"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("kiosk_id"),
    )
    op.create_table(
        "roles",
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("role_name", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("role_id"),
        sa.UniqueConstraint("role_name"),
    )
    op.create_table(
        "lockers",
        sa.Column("locker_id", sa.UUID(), nullable=False),
        sa.Column("kiosk_id", sa.UUID(), nullable=False),
        sa.Column("logical_number", sa.Integer(), nullable=False),
        sa.Column(
            "locker_status",
            sa.Enum(
                "AVAILABLE",
                "OCCUPIED",
                "MAINTENANCE",
                "ERROR_OPEN",
                name="lockerstatus",
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["kiosk_id"],
            ["kiosks.kiosk_id"],
        ),
        sa.PrimaryKeyConstraint("locker_id"),
    )
    op.create_table(
        "users",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("nfc_tag_id", sa.String(length=100), nullable=True),
        sa.Column("pin_hash", sa.String(length=255), nullable=False),
        sa.Column("failed_login_attempts", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("ban_reason", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.role_id"],
        ),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("nfc_tag_id"),
    )
    op.create_table(
        "assets",
        sa.Column("asset_id", sa.UUID(), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=False),
        sa.Column("locker_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("aztec_code", sa.String(length=100), nullable=False),
        sa.Column(
            "asset_status",
            sa.Enum(
                "AVAILABLE",
                "BORROWED",
                "RESERVED",
                "MAINTENANCE",
                "LOST",
                name="assetstatus",
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.category_id"],
        ),
        sa.ForeignKeyConstraint(
            ["locker_id"],
            ["lockers.locker_id"],
        ),
        sa.PrimaryKeyConstraint("asset_id"),
        sa.UniqueConstraint("aztec_code"),
    )
    op.create_table(
        "audit_logs",
        sa.Column("audit_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("action_type", sa.String(length=100), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("previous_hash", sa.String(length=64), nullable=False),
        sa.Column("current_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("audit_id"),
    )
    op.create_table(
        "loans",
        sa.Column("loan_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("asset_id", sa.UUID(), nullable=False),
        sa.Column("checkout_locker_id", sa.UUID(), nullable=False),
        sa.Column("return_locker_id", sa.UUID(), nullable=True),
        sa.Column("reserved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("borrowed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("due_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("returned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "loan_status",
            sa.Enum(
                "RESERVED",
                "ACTIVE",
                "OVERDUE",
                "COMPLETED",
                "FRAUD_SUSPECTED",
                "DISPUTED",
                "PENDING_INSPECTION",
                name="loanstatus",
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.asset_id"],
        ),
        sa.ForeignKeyConstraint(
            ["checkout_locker_id"],
            ["lockers.locker_id"],
        ),
        sa.ForeignKeyConstraint(
            ["return_locker_id"],
            ["lockers.locker_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("loan_id"),
    )
    op.create_table(
        "ai_evaluations",
        sa.Column("evaluation_id", sa.UUID(), nullable=False),
        sa.Column("loan_id", sa.UUID(), nullable=False),
        sa.Column(
            "evaluation_type",
            sa.Enum("CHECKOUT", "RETURN", name="evaluationtype"),
            nullable=False,
        ),
        sa.Column("photo_url", sa.String(length=255), nullable=False),
        sa.Column("ai_confidence", sa.Float(), nullable=False),
        sa.Column(
            "detected_objects", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("has_damage_detected", sa.Boolean(), nullable=False),
        sa.Column("model_version", sa.String(length=50), nullable=False),
        sa.Column("is_approved", sa.Boolean(), nullable=False),
        sa.Column("rejection_reason", sa.String(length=255), nullable=True),
        sa.Column("analyzed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["loan_id"],
            ["loans.loan_id"],
        ),
        sa.PrimaryKeyConstraint("evaluation_id"),
    )
    op.create_table(
        "damage_reports",
        sa.Column("damage_id", sa.UUID(), nullable=False),
        sa.Column("evaluation_id", sa.UUID(), nullable=False),
        sa.Column("damage_type", sa.String(length=100), nullable=False),
        sa.Column("severity", sa.String(length=50), nullable=False),
        sa.Column(
            "segmentation_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("requires_repair", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["evaluation_id"],
            ["ai_evaluations.evaluation_id"],
        ),
        sa.PrimaryKeyConstraint("damage_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("damage_reports")
    op.drop_table("ai_evaluations")
    op.drop_table("loans")
    op.drop_table("audit_logs")
    op.drop_table("assets")
    op.drop_table("users")
    op.drop_table("lockers")
    op.drop_table("roles")
    op.drop_table("kiosks")
    op.drop_table("categories")
    # ### end Alembic commands ###
