"""add_returning_to_loan_status

Revision ID: 5591d67e520a
Revises: aac5afd64c4c
Create Date: 2026-03-18 21:50:47.161421

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "5591d67e520a"
down_revision: str | Sequence[str] | None = "aac5afd64c4c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
