"""add_pending_inspection_and_is_deleted

Revision ID: 887a8f5ec941
Revises: 39d07401d54b
Create Date: 2026-03-13 18:50:03.972454

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "887a8f5ec941"
down_revision: str | Sequence[str] | None = "39d07401d54b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Voeg handmatig de PENDING_INSPECTION waarde toe aan de PostgreSQL enum:
    op.execute("ALTER TYPE assetstatus ADD VALUE IF NOT EXISTS 'PENDING_INSPECTION'")

    # ### commands auto generated by Alembic - please adjust! ###
    # 2. Voeg de kolom toe, MET een server_default (anders crasht postgres op bestaande rijen):
    op.add_column(
        "assets",
        sa.Column(
            "is_deleted", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Note: PostgreSQL enum labels added with ALTER TYPE are not trivially
    # removable. Reverting the addition of the 'PENDING_INSPECTION' label would
    # require creating a new enum type, migrating/CASTing the column(s), and
    # dropping the old type. This is potentially destructive and environment-
    # specific, so this downgrade only removes the additive column we added
    # (`is_deleted`). If you need to fully reverse the enum change, perform
    # careful manual steps and DB backups before doing so.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("assets", "is_deleted")
    # ### end Alembic commands ###
