"""add accepted_privacy_policy

Revision ID: 97fd688f2d9a
Revises: 02d034bcaafd
Create Date: 2026-03-31 10:47:54.522836

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "97fd688f2d9a"
down_revision: str | Sequence[str] | None = "02d034bcaafd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "accepted_privacy_policy",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "accepted_privacy_policy")
    # ### end Alembic commands ###
