"""add uq_kiosk_logical_number to lockers

Revision ID: aac5afd64c4c
Revises: 97af2da80959
Create Date: 2026-03-18 01:26:54.066243

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aac5afd64c4c"
down_revision: str | Sequence[str] | None = "97af2da80959"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_kiosk_logical_number", "lockers", ["kiosk_id", "logical_number"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_kiosk_logical_number", "lockers", type_="unique")
    # ### end Alembic commands ###
